import js from "@eslint/js";
import ts from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import svelte from "eslint-plugin-svelte";
import svelteParser from "svelte-eslint-parser";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default [
	js.configs.recommended,
	{
		ignores: [
			"build/",
			".svelte-kit/",
			"dist/",
			"node_modules/",
			"*.config.*",
			"tests/",
			"coverage/",
			"static/",
			"src/lib/assets/",
			// Generated by `paraglide-js compile` on every check, like build/ and .svelte-kit/. Its
			// files open with an `/* eslint-disable */` header that this config has no rule for, so
			// every one of them reported an "unused eslint-disable directive" warning - 69 of them,
			// growing by one per message key added, and none of them actionable.
			"src/lib/paraglide/",
		],
	},
	{
		files: ["**/*.js", "**/*.ts"],
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: "module",
			parser: tsParser,
			parserOptions: {
				extraFileExtensions: [".svelte"],
			},
			globals: {
				...globals.browser,
				...globals.es2017,
				...globals.node,
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		rules: {
			...ts.configs.recommended.rules,
			"@typescript-eslint/no-unused-vars": [
				"warn",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
				},
			],
		},
	},
	{
		files: ["**/*.svelte"],
		// eslint-plugin-svelte filters suppressed messages in this processor's `postprocess`, so
		// WITHOUT it `svelte/comment-directive` reports nothing and `<!-- eslint-disable ... -->`
		// inside markup is silently inert - a disable comment that reads as applied and is not.
		processor: "svelte/svelte",
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: "module",
			parser: svelteParser,
			parserOptions: {
				parser: tsParser,
				extraFileExtensions: [".svelte"],
			},
			globals: {
				...globals.browser,
				...globals.es2017,
			},
		},
		plugins: {
			svelte,
			"@typescript-eslint": ts,
		},
		rules: {
			// `svelte.configs.recommended` is an ARRAY of flat configs in eslint-plugin-svelte 3,
			// so `.rules` is undefined and this spread has always contributed NOTHING. The
			// recommended set is therefore off, and the two rules below are the whole Svelte
			// ruleset this repo runs. Measured 2026-08-19: turning the real set on reports 17
			// errors, 14 of them `no-navigation-without-resolve` across eight components - a
			// refactor of its own, filed in docs/wiki/backlog.md rather than smuggled in here.
			...svelte.configs.recommended.rules,
			// What makes `<!-- eslint-disable-next-line -->` work inside markup at all. Without it
			// a template warning cannot be suppressed anywhere, however well justified.
			"svelte/comment-directive": "error",
			...ts.configs.recommended.rules,
			"@typescript-eslint/no-unused-vars": [
				"warn",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
				},
			],
			"svelte/no-at-html-tags": "warn",
		},
	},
	prettier,
];
